### ISSUE TITLE
Allow to disable ClickHouse

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/helm-charts#1]
We should allow to disable ClickHouse StatefulSet in https://github.com/uptrace/helm-charts/blob/master/charts/uptrace/templates/clickhouse-statefulset.yaml via a configuration option.

**Comment by vmihailenco** [comment]
You can now disable ClickHouse likes this:

```yaml
clickhouse:
  enabled: false

uptrace:
  config:
    ch:
      addr: clickhouse-host:9000
      user: default
      password:
      database: uptrace
```
