### ISSUE TITLE
Reloading uptrace UI while using multiple pods produces different results

### ISSUE THREAD

**Issue by alexandrujieanu** [uptrace/helm-charts#14]
Hello,

Do you have any idea why this is happening?

[Screencast from 2023-05-10 14-04-58.webm](https://github.com/uptrace/helm-charts/assets/18589491/bcafb14f-a4c7-4d23-ae66-888be41349df)

I'm accessing the service and landing on different pods.

```
kubectl -n uptrace get all

NAME                       READY   STATUS    RESTARTS   AGE
pod/uptrace-0              1/1     Running   0          24h
pod/uptrace-1              1/1     Running   0          24h
pod/uptrace-2              1/1     Running   0          24h
pod/uptrace-postgresql-0   1/1     Running   0          24h

NAME                         TYPE           CLUSTER-IP       EXTERNAL-IP                                                                   PORT(S)                         AGE
service/uptrace              LoadBalancer   10.100.128.181   k8s-uptrace-uptrace-a10XXXX.elb.REGION.amazonaws.com   443:32203/TCP,14317:32604/TCP   24h
service/uptrace-postgresql   LoadBalancer   10.100.247.48    a8e5ff192b5fYYYYY.REGION.elb.amazonaws.com         5432:32391/TCP                  24h

NAME                                  READY   AGE
statefulset.apps/uptrace              3/3     24h
statefulset.apps/uptrace-postgresql   1/1     24h

```

Uptrace `values.yaml`:
```
service:
  type: LoadBalancer
  http_port: 443
  grpc_port: 14317
  loadBalancerSourceRanges:
  %{~ for subnet in allowed_subnets ~}
    - ${ subnet }
  %{~ endfor ~}
  annotations: {}

uptrace:
  config:
    ch:
      addr: clickhouse-headless.clickhouse.svc:9000
      user: ${clickhouse_username}
      password: ${clickhouse_password}
      database: uptrace
      max_execution_time: 30s

    ch_schema:
      compression: ZSTD(3)
      replicated: false
      spans:
        storage_policy: 'default'
        ttl_delete: 14 DAY
      metrics:
        storage_policy: 'default'
        ttl_delete: 14 DAY
```

Clickhouse:
```
kubectl -n clickhouse get pods

NAME                     READY   STATUS    RESTARTS   AGE
clickhouse-shard0-0      1/1     Running   0          23h
clickhouse-shard0-1      1/1     Running   0          23h
clickhouse-shard0-2      1/1     Running   0          23h
clickhouse-zookeeper-0   1/1     Running   0          23h
clickhouse-zookeeper-1   1/1     Running   0          23h
clickhouse-zookeeper-2   1/1     Running   0          23h
```

Thank you.
