### ISSUE TITLE
Unable to set external postgress credentials via secrets

### ISSUE THREAD

**Issue by numfin** [uptrace/helm-charts#16]
As title said: helm expects from me `user` and `password` in plain text. I want to set the values via secrets

**Comment by vmihailenco** [comment]
@numfin could you try to prepare a PR?

**Comment by numfin** [comment]
@vmihailenco oki. I'll try to find what i can do

**Comment by caique-franca** [comment]
@numfin , I'm also interested in this feature. Have you already started to develop something?
Another feature similar to the one proposed here that I'm interested in is the possibility of configuring the credentials of an external clickhouse via secrets.

**Comment by numfin** [comment]
@caique-franca not yet. Too busy :D ill sit today maybe. add me at discord: `nextgensamurai`

**Comment by numfin** [comment]
@vmihailenco uptrace expects pg/ch config via uptrace.yml
Is there any chance uptrace could recieve secrets via env?

**Comment by vmihailenco** [comment]
You can use environment variables in the YAML config file, for example:

```yaml
pg:
  addr: ${UPTRACE_PG_ADDR}
  user: ${UPTRACE_PG_USER}
  password: ${UPTRACE_PG_PASSWORD}
  database: ${UPTRACE_PG_DATABASE:uptrace}
```

You can specify a default value for environment variables, for example, `${ENV_VAR_NAME:default_value}`.

@numfin does that help here?
