### ISSUE TITLE
Uptrace does not work correctly when the replicated parameter is set to true.

### ISSUE THREAD

**Issue by caique-franca** [uptrace/helm-charts#18]
@vmihailenco,

As we talked on Telegram (https://t.me/uptrace/1455), below is the step by step to reproduce the Uptrace problem when we try to use it with the clickhouse provided by bitnami (https://github.com/bitnami/charts/tree/main/bitnami/clickhouse).

Step 1) Create the Uptrace namespace.

Step 2) Deploy the clickhouse.

clickhouse-values.yaml
```
global:
  storageClass: efs
shards: 1
auth:
  username: default
  password: dE157D3MTp
```

Observation.: The clusters here at the company use the storageClass efs, but I believe that you can carry out your test with the storageClass of your choice.

uptrace-values.yaml
```
uptrace:
  config:
    ch:
      addr: clickhouse-headless:9000
      user: default
      password: dE157D3MTp
      database: default
    ch_schema:
      replicated: true
      cluster: default
clickhouse:
  enabled: false
replicaCount: 3
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
    - host: uptrace.dev.internal
      paths:
        - path: /
          pathType: Prefix
```

I used the commands below to deploy clickhouse and uptrace.:
* helm install -n uptrace uptrace uptrace/uptrace -f uptrace-values.yaml
* helm install -n uptrace clickhouse oci://registry-1.docker.io/bitnamicharts/clickhouse -f clickhouse-values.yaml

When accessing the Uptrace interface you will see the error "DB::Exception: Table default.spans_index_buffer_dist doesn't exist"

![image](https://github.com/uptrace/helm-charts/assets/63365577/ab732e15-f270-4a85-bbce-79e0f558236e)

I understand that @alexandrujieanu is trying to deploy Uptrace the same way I am and has also encountered problems. Here are the problems opened by him.:
https://github.com/uptrace/helm-charts/issues/12
https://github.com/uptrace/helm-charts/issues/14

**Comment by caique-franca** [comment]
What did you find when you configured the ingress? Was it the same problem that happened to me?

I did the following test.:

1) I deployed Uptrace without ingress settings.
2) I noticed that Uptrace ran successfully.
3) I updated the uptrace-values.yaml with the ingress settings and ran the "helm upgrade" command.
4) The ingress was created and the uptrace continued to work.

For some reason, if we create the ingress after Uprace, the problem does not appear.

So I decided to do a second test.:

1) I deployed Uptrace with the settings below, I just replaced the ingress with a loadbalancer service.
```
uptrace:
  config:
    ch:
      addr: clickhouse-headless:9000
      user: default
      password: dE157D3MTp
      database: default
    ch_schema:
      replicated: true
      cluster: default
clickhouse:
  enabled: false
replicaCount: 3
service:
  type: LoadBalancer
  port: 80
  loadBalancerSourceRanges:
    - '0.0.0.0/0'
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```

2) The uptrace PODS are running, but they have several errors in the logs and it is not possible to verify the traces through the WEB interface.

```
│ [ch]  15:13:33.137   INSERT                8.403ms  INSERT INTO "spans_index_buffer_dist" ("id", "parent_id", "trace_id", "project_id", "type", "system", "group_id", "kind", "name", "event_name", "display_name", "time", "duration", "status_code", "status_message", "count", "l ││ 2023-08-10T15:13:33.137Z    error    tracing/span_processor.go:232    ch.Insert failed    {"error": "DB::Exception: Table default.spans_index_buffer doesn't exist", "table": "spans_index"}
````

For some reason deploying Uptrace with 3 replicas and replication settings along with ingress or a loadbalancer service causes a problem for uptrace.
