### ISSUE TITLE
SSLmode for pg

### ISSUE THREAD

**Issue by mkherlakian** [uptrace/helm-charts#19]
I'm trying to connect to a PG server that forces sslmode (connection dsn has sslmode=require). There doesn't seem to be a way in the helm override file to specify that option.

Is there any way to set that option in the overrides file?

**Comment by mkherlakian** [comment]
As a follow up, I see [here](https://github.com/uptrace/uptrace/blob/87cebed4f65bff815e63a9b09368fb5ac9e30cf7/pkg/bunconf/config.go#L427) that one can define a DSN for PG. Any way to make that work from a heml override? I tried setting dsn under pg, but that didn't work.

**Comment by vmihailenco** [comment]
You try to override it in the values:

```
uptrace:
  config:
    pg:
      dsn: your-dsn-with-sslmode
```

**Comment by mkherlakian** [comment]
I tried that, but it doesn't seem to want to take it. It uses the default values instead...

**Comment by mkherlakian** [comment]
One possible explanation is that since there's a default config applied here:
https://github.com/uptrace/uptrace/blob/87cebed4f65bff815e63a9b09368fb5ac9e30cf7/pkg/bunconf/config.go#L59-L63

The DSN is ignored altogether? The helm chart won't properly render the dsn option (if you supply it and look at the resulting configmap it won't be there). However, i tried modifying the configmap by hand to read:
pg:
  dsn: <dsn_string>

or
pg:
  config:
    dsn: <dsn_string>

and they both don't work...

**Comment by vmihailenco** [comment]
@mkherlakian you can also try this:

```
uptrace:
  config:
    pg:
      tls: {}
      #tls: { insecure_skip_verify: true }
```

**Comment by mkherlakian** [comment]
That did it @vmihailenco ! (though I did have to specify insecure_skip_verify: true, because otherwise it complained that I had to specify ServerName or InsecureSkipVerify, so still have to figure that out). I had to do the same for Clickhouse.

That said I think it would be nice to be able to specify the DSN...

**Comment by xvilo** [comment]
Thanks, I was also on the wrong track here and trying the same thing with the DSN. To be help out others in the future, when setting up **Uptrace with Zalando's Postgres Operator** do the following:
```yaml
uptrace:
  config:
    pg:
      addr: '[cluster name here]:5432'
      database: '[change]'
      password: '[change]'
      user: '[change]'
      tls: { insecure_skip_verify: true }
```
