### ISSUE TITLE
405 error in Uptrace hosted on Kubernetes

### ISSUE THREAD

**Issue by nclsmitchell** [uptrace/helm-charts#26]
Hello,

I have installed an Uptrace instance in my Kubernetes cluster using the helm chart and the following override values:

```
uptrace:
  config:
    service:
      telemetry:
        logs:
          level: 'debug'
    projects:
      - id: 1
        name: $PROJECT_NAME
        token: $TOKEN
        pinned_attrs:
          - service.name
          - host.name
          - deployment.environment
   
    auth:
      users:
        - name: $USER
          email: $EMAIL
          password: $PASSWORD
          notify_by_email: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: $UPTRACE_ADDRESS
    networking.gke.io/managed-certificates: $UPTRACE_CERT
  hosts:
    - host: $HOSTNAME
      paths:
        - path: /
          pathType: Prefix
```

Then I have followed the FastAPI [documentation](https://uptrace.dev/get/instrument/opentelemetry-fastapi.html#opentelemetry-sdk) in order to add a FastAPI Instrumentor, giving the following code extract:

```
from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor

# Configure trace provider and exporter
trace.set_tracer_provider(TracerProvider())
tracer = trace.get_tracer(__name__)

# Replace with your Uptrace DSN and endpoint
otlp_exporter = OTLPSpanExporter(
    endpoint="http://$HOSTNAME",
    headers=(("uptrace-dsn", "http://$TOKEN@$HOSTNAME?grpc=14317"),)
)

span_processor = BatchSpanProcessor(otlp_exporter)
trace.get_tracer_provider().add_span_processor(span_processor)

api = FastAPI(title="api")
FastAPIInstrumentor.instrument_app(api)
```

I then added the following route:

```
from opentelemetry import trace

tracer = trace.get_tracer(__name__)

@router.post("/route")
async def search():
    with tracer.start_as_current_span("route"):
       return {"message": "Hello, World!"}
```

But when I am calling the route I have the following error in my console:

```
Failed to export traces to uptrace.juisci.com, error code: StatusCode.UNKNOWN
Traceback (most recent call last):
  File "$VIRTUALENV_PATH/lib/python3.11/site-packages/opentelemetry/exporter/otlp/proto/grpc/exporter.py", line 262, in _export
    self._client.Export(
  File "$VIRTUALENV_PATH/lib/python3.11/site-packages/grpc/_channel.py", line 1160, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$VIRTUALENV_PATH/lib/python3.11/site-packages/grpc/_channel.py", line 1003, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Received http2 header with status: 405"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-01-15T17:53:40.170282+01:00", grpc_status:2, grpc_message:"Received http2 header with status: 405"}"
>
```

And I have the following logs in my uptrace container in Kubernetes:
```
[bunrouter]  16:53:50.151  17aa938a134f557f1743c10d47a73ac8   405          9µs   POST     /opentelemetry.proto.collector.trace.v1.TraceService/Export
```

Could someone explain what I have done wrong in my confirguration?

Thanks!

**Comment by vmihailenco** [comment]
In your configuration, replace the `service.name` with `service_name` and do the same conversion for other attributes.

In your Python example, you should either use [uptrace-python](https://github.com/uptrace/uptrace-python) or learn on which port Uptrace API is available [here](https://uptrace.dev/get/install.html#start-sending-data).

Specifically, this line is missing any ports:

```
endpoint="http://$HOSTNAME",
```

But it should use `:14317` to use GRPC API. See [this](https://uptrace.dev/get/opentelemetry-python.html#exporting-traces) as well.

**Comment by nclsmitchell** [comment]
Hello @vmihailenco,

I am a bit confused. When I am adding the `:1417` port on  `endpoint="http://$HOSTNAME"` I get a timeout error.

I also tried to directly use `uptrace-python` following the FastAPI example:

```
import uptrace
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor

api = FastAPI(title="api")

uptrace.configure_opentelemetry(
    dsn="http://$TOKEN@$HOSTNAME?grpc=14317",
    service_name="$PROJECT_NAME",
    service_version="1.0.0",
    deployment_environment="staging"
)
FastAPIInstrumentor.instrument_app(api)

def post_fork(server, worker):
    uptrace.configure_opentelemetry(...)
```

But the last solution do not send anything to my hosted uptrace app.

Am I doing this wrong?

I am using the simplified `override-values.yaml` in my helm install:
```
uptrace:
  config:
    service:
      telemetry:
        logs:
          level: 'debug'
    projects:
      - id: 1
        name: $PROJECT_NAME
        token: $TOKEN

    auth:
      users:
        - name: $USER
          email: $EMAIL
          password: $PASSWORD!
          notify_by_email: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: $UPTRACE_ADDRESS
    networking.gke.io/managed-certificates: $UPTRACE_CERT
  hosts:
    - host: $HOSTNAME
      paths:
        - path: /
          pathType: Prefix
```

Thank you in advance!
