### ISSUE TITLE
Values(otelcol.otlpExporter.endpoint): Does not have any effect on the template,

### ISSUE THREAD

**Issue by Khalid-Nowaf** [uptrace/helm-charts#48]
I have changed the default values as the following:
```yaml
otelcol:
  enabled: false 

  otlpExporter:
    endpoint: http://uptrace:14317 # <---- HERE instead of http://my-uptrace:14317
    tls: { insecure: true }
    headers: { 'uptrace-dsn': 'http://project1_secret_token@localhost:14317/1' } 
```

So as expect the collector to export to `uptrace:14317`, but the collector actually trying to connect to `my-trace:14317`

```log
... error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: lookup my-uptrace on 10.43.0.10:53: no such host\"", "dropped_items": 1387} ..

```
and I can see the template in the following file charts/uptrace/templates/otelcol-config.yaml has the config map as
``` yaml
{{ if .Values.otelcol.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcontribcol
  labels:
    app: otelcontribcol
    {{- include "uptrace.labels" . | nindent 4 }}
data:
  config.yaml: |
    receivers:
 ...
    exporters:
      debug:
      otlp/local:
        endpoint: http://my-uptrace:14317
        tls: { insecure: true }
        headers: { 'uptrace-dsn': 'http://project1_secret_token@localhost:14317/1' }
    service:
     ...
{{ end }}
```
