### ISSUE TITLE
The gRPC port is not accessible

### ISSUE THREAD

**Issue by alexandrujieanu** [uptrace/helm-charts#6]
The http port is defined in the [statefulset](https://github.com/uptrace/helm-charts/blob/master/charts/uptrace/templates/uptrace-statefulset.yaml#L42-L45), but the gRPC port is not. Similarly, the http port is exposed in the [service](https://github.com/uptrace/helm-charts/blob/master/charts/uptrace/templates/service.yaml#L15-L18), but the gRPC is not. I can open a PR for this change.

Also, I think the two service ports should also be part of the statefulset template and of the uptrace config, so that the same port is used end to end and a user can copy-paste the `UPTRACE_DSN` he sees in Uptrace.

For example, my uptrace is accessible at `https://uptrace.xxx.yyy` (on port 443) and users see:
![image](https://user-images.githubusercontent.com/18589491/224080216-e61ee018-01fe-4bf3-958d-5dccc8d4ac0a.png)

Users need to replace `localhost` with the actual address which is not ideal, but easy to figure out, compared to realizing that they need to use port 443 (or 80) instead of 14318. I also would also liked Uptrace more if it showed 443 in the text instead of 14318 which seems hardcoded.

My service:

```
    ports:
    - name: http
      nodePort: 31386
      port: 443
      protocol: TCP
      targetPort: http
    - name: grpc
      nodePort: 31524
      port: 14317
      protocol: TCP
      targetPort: grpc
```
statefulset:

```
        ports:
        - containerPort: 443
          name: http
          protocol: TCP
        - containerPort: 14317
          name: grpc
          protocol: TCP
```

and the pods:
```
tcp        0      0 :::14317                :::*                    LISTEN      13/uptrace
tcp        0      0 :::443                  :::*                    LISTEN      13/uptrace
```
